# Generated by Django 5.0.2 on 2025-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='decision_timeframe',
            field=models.CharField(blank=True, help_text='Timeframe for making investment decisions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='existing_debts',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total outstanding debts', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='existing_investments',
            field=models.TextField(blank=True, help_text='Description of any existing investments', null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='interested_investments',
            field=models.CharField(blank=True, help_text='Comma-separated list of investment types of interest', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('none', 'No Experience'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='investment_horizon',
            field=models.CharField(blank=True, choices=[('short', 'Short Term (0-2 years)'), ('medium', 'Medium Term (3-5 years)'), ('long', 'Long Term (6-10 years)'), ('very_long', 'Very Long Term (10+ years)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='investment_restrictions',
            field=models.TextField(blank=True, help_text='Any specific investment restrictions or preferences', null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly living expenses', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='monthly_investment_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount available to invest monthly', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='savings_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage of income saved monthly', null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='socially_responsible',
            field=models.BooleanField(default=False, help_text='Preference for socially responsible investing'),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='tax_considerations',
            field=models.TextField(blank=True, help_text='Any tax considerations that might affect investment choices', null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, help_text='Annual gross income', max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='investment_goal',
            field=models.CharField(choices=[('retirement', 'Retirement'), ('wealth', 'Wealth Building'), ('education', 'Education'), ('home', 'Home Purchase'), ('emergency', 'Emergency Fund'), ('travel', 'Travel'), ('business', 'Business Startup'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='risk_tolerance',
            field=models.CharField(choices=[('very_low', 'Very Low Risk'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='savings',
            field=models.DecimalField(decimal_places=2, help_text='Current savings amount', max_digits=12),
        ),
    ]
