# Generated by Django 5.0.2 on 2025-05-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_financialprofile_decision_timeframe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprofile',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='decision_timeframe',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='existing_debts',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='existing_investments',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='interested_investments',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='investment_experience',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='investment_goal',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='investment_horizon',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='investment_restrictions',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='monthly_investment_capacity',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='savings',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='savings_rate',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='socially_responsible',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='tax_considerations',
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='current_debts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='debt_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='emotional_stability',
            field=models.CharField(choices=[('1', 'Very Emotionally Sensitive'), ('2', 'Somewhat Emotionally Sensitive'), ('3', 'Neutral'), ('4', 'Somewhat Emotionally Stable'), ('5', 'Very Emotionally Stable')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='family_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='has_investment_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='investment_knowledge',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert'), ('5', 'Extremely Expert')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='long_term_goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='long_term_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='medium_term_goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='medium_term_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='other_assets',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='previous_investments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='retirement_plans',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='short_term_goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='short_term_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='risk_tolerance',
            field=models.CharField(choices=[('1', 'Very Conservative'), ('2', 'Conservative'), ('3', 'Neutral'), ('4', 'Aggressive'), ('5', 'Extremely Aggressive')], max_length=1),
        ),
    ]
