# Generated by Django 5.0.2 on 2025-05-17 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_remove_financialprofile_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentadvice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='emotional_stability',
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Annual income cannot be negative')]),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='investment_goal',
            field=models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('education', 'Education Funding'), ('home', 'Home Purchase'), ('other', 'Other Goals')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='savings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Savings cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, message='You must be at least 18 years old'), django.core.validators.MaxValueValidator(100, message='Please enter a valid age')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='current_debts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Current debts cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='debt_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Debt interest rate cannot be negative'), django.core.validators.MaxValueValidator(100, message='Debt interest rate cannot exceed 100%')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='family_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Family size must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='long_term_goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Goal amount cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='medium_term_goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Goal amount cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Monthly expenses cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Monthly income cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Monthly savings cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='short_term_goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Goal amount cannot be negative')]),
        ),
    ]
